version: "3.8"

services:
  #server:
  #  build:
  #    context: ./server/
  #    dockerfile: Dockerfile.server
  #  networks:
  #    - internal_network

  server:
    build:
      context: ../
      dockerfile: ./docker_testing/server/Dockerfile.our_server
    networks:
      - internal_network
    volumes:
      - data:/repo

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile.client
    networks:
      - internal_network
    stdin_open: true
    tty: true

volumes:
  data:
    name: "datada"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ../

networks:
  internal_network:
    internal: true
    driver: bridge
