version: "3.8"

services:
  #server:
  #  build:
  #    context: ./server/
  #    dockerfile: Dockerfile.server
  #  networks:
  #    - internal_network

  server:
    build:
      context: ../
      dockerfile: ./docker_testing/server/Dockerfile.our_server
    networks:
      - internal_network

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile.client
    networks:
      - internal_network
    stdin_open: true
    tty: true

networks:
  internal_network:
    internal: true
    driver: bridge
