FROM python:3.9-slim

RUN apt-get update && \
	apt-get install -y curl bsdextrautils neovim && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY server.py .

EXPOSE 8080
CMD ["python", "server.py"]

