FROM gcc:latest

RUN apt-get update \
    && apt-get install -y \
        curl \
        bsdextrautils \
		build-essential
#    && apt-get clean \
#    && rm -rf /var/lib/apt/lists/* \


WORKDIR /webserv
COPY . .

EXPOSE 8080
CMD ["sleep", "infinity"]
#CMD ["sh", "-c", "make && ./webserv"]

